name: Github Actions
run-name: Started deploying
on:
  push:
    branches:
      - Backend
jobs:
  Deployin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"


