name: Github Actions
run-name: Started deploying
on:
  push:
    branches:
      - Backend
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
  Deploy:
    needs: Test
    runs-on: self-hosted
    steps:
      - name: Docker Login
        run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
      
      - name: Deploy Compose
        run: pwd
     
      - name: Deploy Composee
        run: ls -a
